apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jyeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jyeb
    app.kubernetes.io/part-of: byoc-app-mrsl
  name: jyeb
spec:
  rules:
  - host: jyeb-byoc-sknb-tenant.apps.cf07706ef81f0b4a1aab.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: jyeb
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
