apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jyeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jyeb
    app.kubernetes.io/part-of: byoc-app-mrsl
  name: jyeb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: jyeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: jyeb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-sknb-tenant/byoc-app-mrsl/jyeb@sha256:5b88ad8baedd59f3c5c185aaf36180098b68e377734e2ee936c607393c5de9f0
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
